### ISSUE TITLE
The executable file openspa-server cannot be opened with the screen

### ISSUE THREAD

**Issue by Mingcat-23** [greenstatic/openspa#1]
sudo screen -d -m ~/openspa/openspa-server start
do not have any response.
I am using ubunt20.0 in VMware 16.0

**Comment by greenstatic** [comment]
Have you followed the [instructions](https://github.com/greenstatic/openspa/blob/master/docs/OpenSPA%20Server%20Installation%20with%20iptables.md) carefully? Check the output of the command (attach to the screen session).

The project was written when an older version of Go was available, if I'm not mistaken it was v1.10 (current release is v1.15). I have gotten reports that there have been some minor changes to the x509 certificate library which may cause issues like the one you are experiencing. 

In the coming months I plan on reviving this project and much refactoring is going to happen. Including fixing all the issues caused by the newer version of Go, improving documentation, new features, etc.

**Comment by snoweunyoung** [comment]
@Mingcat-23 `sudo screen -L -d -m ./openspa-server start`
It work for me.
